name: Django Tests

on: [push,pull_request]
 
jobs:
  build:

    runs-on: ubuntu-latest

    step:
    - uses: actions/checkout@v2
    - name: set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install dependencies
      run:  |  
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage report
      run:  |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run:  |
        python3 manage.py test





